version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - lc
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin

  front:
    container_name: front
    build:
      context: ./FRONT
      dockerfile: Dockerfile
    volumes:
      - '.:/node_modules'
    ports:
      - 3000:3000
    networks:
      - lc
    links:
      - 'back'
    
  back:
    container_name: back
    build:
      context: ./BACK
      dockerfile: Dockerfile
    volumes: 
      - '.:/node_modules'
    ports:
      - 5000:5000
    networks:
      - lc
    links:
      - 'postgres'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}

networks:
  lc:
    driver: bridge

volumes:
  postgres:
  pgadmin:
